name: marvel
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  crypto: ^3.0.1
  intl: ^0.17.0
  
  # Image
  cached_network_image: ^3.2.1

  # Network
  dio: ^4.0.6

  # State Managements
  mobx: ^2.0.7+2
  flutter_mobx: ^2.0.6+1
  build_runner: ^2.1.11
  mobx_codegen: ^2.0.7
  provider: ^6.0.2


flutter_icons:
  image_path: "assets/icon/icon.png"
  android: true
  ios: true
  macos: true
  windows: true
  web: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons_maker: ^0.10.2

flutter:
  uses-material-design: true
  assets:
      - assets/images/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
